<!DOCTYPE html>
<html lang="en-US"><!-- InstanceBegin template="/Templates/inner-page.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Global Opportunities</title>
<meta name="description" content=""/>
<meta name="keywords" content=""/>
<!-- InstanceEndEditable -->
<link rel="stylesheet" href="<?php echo base_url();?>application/css/styles.css" type="text/css" media="screen"/>
 <link rel="stylesheet" href="<?php echo base_url();?>application/css/museo.css" type="text/css" media="screen"/>
<link href="/favicon.ico" type="image/ico" rel="shortcut icon"/>
 <link rel="stylesheet" href="<?php echo base_url();?>application/css/bootstrap.css" type="text/css" media="screen"/>
<script src="<?php echo base_url();?>application/js/jquery-1.12.0.min.js"></script>
<script src="<?php echo base_url();?>application/js/bootstrap.js"></script>
<!-- InstanceBeginEditable name="head" -->
<!-- InstanceEndEditable -->
</head>

<body>
<div class="main_container">
		
<!-- InstanceBeginEditable name="MainContainer" -->
	<div id="globalOppertunity">
		<div class="innerPageBanner clearfix">
		<img src="<?php echo base_url();?>application/images/banners/global-oppertunities.jpg" alt="Global Opportunities from BDIHub">
		</div>
		<div class="contentBlock">
		<div class="spacer40"></div>
		<div class="wrapper1000">
		<div class="row center-md">
			<div class="col-md-12">
			<div class="introBox">
			<h1 class="title">Global Opportunities from BDIHub</h1>
				<p>BDIHub opens up a world of employment possibilities to empower professionals and businesses in the 
competitive Big Data and Analytics industry. Organizations are adapting their infrastructures to support the large amounts of data being generated by their business, and instead of allowing this information to go unused, they are finding opportunities to understand, interpret, and gain valuable insights that support business innovation.</p>
				<p>BDIHub can provide you with the tools you need to succeed in a data-driven business world with a network of industry experts, an extensive tool set, and customized training to help you advance a career in the 
competitive global Data Science industry.</p>
				</div>
			</div>
		</div>
		</div>
		<div class="spacer80"></div>
		<div class="row middle-xs start-md start-lg imageHighlight green">
					<div class="col-md-6 col-sm-4"><img src="<?php echo base_url();?>application/images/big-data-innovation.jpg" alt="Big Data Innovation and Job Opportunities" width="735" height="592" title="Big Data Innovation and Job Opportunities"></div>
					<div class="col-md-6 col-sm-8">
				  <div class="box textBlock">
				  	<h2 class="titleSub01">Big Data Innovation and <br />
Job Opportunities</h2>
				  	<p>The world is constantly changing, and so is data. More data is being generated from businesses, mobile devices, computers, machine equipment, and people every day, and it continues to grow at an astonishing rate. Data scientists have found unique ways to utilize this information for transformative effect, and the data-driven business market has grown accordingly.</p>
				  	<p>The North American market is eager to gain knowledgeable Data Scientists from convenient near-shore establishments, and the exciting job opportunities correspond to the following innovative data solutions:</p>
				  </div>
				  </div>
				</div>
		<div class="spacer40"></div>
			<div class="wrapper">
				<div class="row between-lg start-xs center-md center-lg" id="serviceHighlight">
						<div class="col-md-3 col-sm-6">
						<div class="serviceBlock">
							<div class="titleService">Search Pattern Analysis</div>
							<p>Companies like Google and Bing are helping customers to find what they are searching for on the web by using the algorithms designed on the basis of search patterns. These search engines also predict suggestions on what they want to search for.</p>
					</div>
						</div>
						<div class="col-md-3 col-sm-6">
						<div class="serviceBlock">
							<div class="titleService">Personalized Experiences</div>
							<p>Netflix, Amazon, and Spotify are leading the way for the companies that give the best customer experiences. These organizations use data as a means to better understand customer behavior to give you an individualized experience.</p>
						</div>
						</div>
						<div class="col-md-3 col-sm-6">
						<div class="serviceBlock">
							<div class="titleService">Navigation</div>
							<p>Uber, Deliveroo, and Google Maps use machine learning algorithms derived from data patterns to better locate your position, and provide optimal routes when traveling. Get where you need to go faster with the power of big data.</p>
						</div>
						</div>
						<div class="col-md-3 col-sm-6">
						<div class="serviceBlock">
							<div class="titleService">Business Solutions</div>
							<p>Whether you are an enterprise level business, or a small family owned operation, data is giving organizations a valuable insight into customer behavior, trends, risks, and opportunities that help drive successful business outcomes.</p>
						</div>
						</div>
					</div>
			</div>
			
		<div class="fullBgContainer" id="jobTitles">
		
		
		</div>
	  </div>
		  <div class="row reverse middle-xs start-md start-lg imageHighlight blue">
		  <div class="col-md-6 col-sm-3"><img src="<?php echo base_url();?>application/images/customized-support.jpg" alt="Customized Support" title="Customized Support from BDIHub"></div>
					<div class="col-md-6 col-sm-9">
				  <div class="box textBlock">
				  	<h2 class="titleSub01">Customized Support <br />
from BDIHub</h2>
				  	<p>Data Science is one of the fastest growing global industries, and offers lucrative and agile career opportunities for the future. With a diverse variety of flexible career options, Data Science is a profession that provides an area of interest for everyone.</p>
				  	<p>BDIHub is a global entity positioned to help businesses and professionals with education and training for an effortless integration into a corporate environment. Whatever your skills, interests, or professional goals, BDIHub is ready to assist you in leveraging data for a rewarding career. Sign up today to learn more about BDIHub’s business and professional opportunities. </p>
				  </div>
				  </div>
				</div>
		</div>
		</div>
	<!-- InstanceEndEditable -->
	
	</div>
<!-- InstanceBeginEditable name="FooterScriptRegion" -->FooterScriptRegion<!-- InstanceEndEditable -->
	
	</body>
<!-- InstanceEnd --></html>
